
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiDOxjfvz1Efj9OBwALZHHV-e31rKXMdU',
    authDomain: 'health-tracker-478aa.firebaseapp.com',
    databaseURL: 'https://health-tracker-478aa-default-rtdb.firebaseio.com',
    projectId: 'health-tracker-478aa',
    storageBucket: 'health-tracker-478aa.appspot.com',
    messagingSenderId: '266707017893',
    appId: '1:266707017893:web:4320a64961a303d41c6d4c',
    measurementId: 'G-FWJPJVPNGV'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp7T7ml9FniZiecpGJUiS0bPLObEADZAc',
    appId: '1:266707017893:android:adb3b9a2bc88eb3c1c6d4c',
    messagingSenderId: '266707017893',
    projectId: 'health-tracker-478aa',
    storageBucket: 'health-tracker-478aa.appspot.com'
  );
}
